# Generated by Django 2.2.1 on 2019-11-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Organization name')),
                ('website', models.CharField(max_length=50, verbose_name='Website')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo_address', models.ImageField(blank=True, upload_to='pictures/organizations', verbose_name='Photo address')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.Organization', verbose_name='Organization ID'),
        ),
    ]
