# Generated by Django 2.2.1 on 2019-11-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_auto_20191106_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register_app.Organization', verbose_name='Organization'),
        ),
    ]
