# Generated by Django 2.2.1 on 2019-12-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_auto_20191201_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('m_filepath', models.FileField(upload_to='')),
                ('receiver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
