# Generated by Django 2.2.1 on 2020-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0008_auto_20200211_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_address',
            field=models.TextField(blank=True, null=True, verbose_name='Photo address'),
        ),
    ]
