# Generated by Django 2.2.1 on 2020-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0010_auto_20200211_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_address',
            field=models.URLField(blank=True, null=True, verbose_name='Photo address'),
        ),
    ]
