# Generated by Django 2.2.1 on 2020-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0012_auto_20200211_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='photo_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo address'),
        ),
    ]
