# Generated by Django 2.2.1 on 2020-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0013_auto_20200211_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='photo_address',
        ),
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
