# Generated by Django 2.2.1 on 2020-03-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0014_auto_20200301_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Password')),
                ('organization_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.Organization', verbose_name='Organization')),
            ],
        ),
    ]
