# Generated by Django 2.2.1 on 2020-04-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0018_auto_20200311_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceevent',
            name='event_id',
        ),
    ]
