# Generated by Django 2.2.1 on 2020-04-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0019_remove_workspaceevent_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceevent',
            name='we_id',
        ),
        migrations.AlterField(
            model_name='workspaceevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Event'),
        ),
    ]
