# Generated by Django 2.2.1 on 2020-04-15 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0020_auto_20200414_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workspace_relation',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_workspace_relation',
            name='w_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace', to='register_app.Workspace'),
        ),
    ]
