# Generated by Django 2.2.1 on 2020-04-24 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0021_auto_20200415_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacepost',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='workspacepost',
            name='wp_id',
        ),
        migrations.AlterField(
            model_name='workspacepost',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Post'),
        ),
    ]
