# Generated by Django 2.2.1 on 2020-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0023_auto_20200424_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pst_filename',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='File name'),
        ),
    ]
