# Generated by Django 2.2.1 on 2020-06-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0027_team_team_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='projectevent',
            name='pe_id',
        ),
        migrations.RemoveField(
            model_name='teamevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='teamevent',
            name='te_id',
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Event'),
        ),
        migrations.AlterField(
            model_name='teamevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Event'),
        ),
    ]
