# Generated by Django 2.2.1 on 2020-06-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0029_auto_20200606_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPostComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Comment')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.TeamPost')),
            ],
            bases=('register_app.comment',),
        ),
        migrations.CreateModel(
            name='ProjectPostComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register_app.Comment')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.ProjectPost')),
            ],
            bases=('register_app.comment',),
        ),
    ]
