# Generated by Django 2.2.1 on 2020-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0031_auto_20200610_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampostcomment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='teampostcomment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
