# Generated by Django 2.2.1 on 2020-06-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0032_auto_20200611_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampostcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='teampostcomment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.TeamPost'),
        ),
    ]
