# Generated by Django 2.2.1 on 2020-06-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0033_auto_20200611_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='m_filepath',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.Conversation'),
        ),
    ]
