# Generated by Django 2.2.1 on 2020-06-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0036_auto_20200613_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
