# Generated by Django 2.2.1 on 2020-06-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0037_message_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='w_manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
