# Generated by Django 2.2.1 on 2020-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0038_workspace_w_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='t_status',
            field=models.CharField(choices=[(0, 'Created'), (1, 'Assigned'), (2, 'In progress'), (3, 'Completed'), (4, 'Submitted')], max_length=10, null=True),
        ),
    ]
