# Generated by Django 2.2.1 on 2020-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0041_auto_20200620_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
