# Generated by Django 2.2.1 on 2020-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0043_auto_20200620_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_filepath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Task assigned file address'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_filepath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Task final file address'),
        ),
    ]
