# Generated by Django 2.2.1 on 2020-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0044_auto_20200620_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
