# Generated by Django 2.2.1 on 2020-06-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0045_task_submitted_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
