# Generated by Django 2.2.1 on 2020-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0047_team_tm_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tm_submitted_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tm_submitted_filepath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Task final file address'),
        ),
    ]
