# Generated by Django 2.2.1 on 2020-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0048_auto_20200709_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_submitted_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='p_submitted_filepath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Task final file address'),
        ),
    ]
