# Generated by Django 2.2.1 on 2020-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0049_auto_20200711_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_submitted_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_submitted_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
